biozherproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('main.urls')),
]

main/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
	path('', HomePageView.as_view(), name = 'home'),
	path('about/', AboutPageView.as_view(), name = 'about'),
	path('documentation/', DocumentationBlockListView.as_view(), name = 'documentation'),
	path('gallery/', TrialsPhotoListView.as_view(), name = 'gallery'),
	path('products/', ProductListView.as_view(), name = 'products'),
	path('blog/', PostListView.as_view(), name = 'blog'),
	path('blog/<int:pk>/', PostDetailView.as_view(), name = 'blog_detail'),
	path('contacts/', ContactPageView.as_view(), name = 'contacts'),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Post(models.Model):

	class Meta:
		verbose_name = "Пост"
		verbose_name_plural = "Посты"

	title = models.CharField(max_length = 255)

	description = models.TextField()

	url = models.URLField()


	def __str__(self):
		return f'Пост с названием \"{self.title}\"'


	def link_for_video(self):
		url = str(self.url)

		video_id = url.split('/')[-1]

		link = 'https://www.youtube.com/embed/' + video_id

		return link


class Product(models.Model):

	class Meta:
		verbose_name = "Продукт"
		verbose_name_plural = "Продукты"

	title = models.CharField(max_length = 255)

	description = models.TextField()

	image = models.ImageField(upload_to = 'imgs/')

	def __str__(self):
		return f'Продукт с названием "{self.title}"'


class DocumentationBlock(models.Model):

	class Meta:
		verbose_name = "Блок документации"
		verbose_name_plural = "Блоки документации"

	title = models.CharField(max_length = 255)

	def __str__(self):
		return f'Блок документации "{self.title}"'


class DocumentationBlockItem(models.Model):

	class Meta:
		verbose_name = "Элемент блока документации"
		verbose_name_plural = "Элементы блока документации"

	documentation_block = models.ForeignKey(DocumentationBlock, on_delete = models.CASCADE)

	file = models.FileField(upload_to = 'documents/')

	def __str__(self):
		return f'Элемент {self.file.name} блока {self.documentation_block}'


class TrialsPhoto(models.Model):

	class Meta:
		verbose_name = "Фото испытаний"
		verbose_name_plural = "Фото испытаний"

	image = models.ImageField(upload_to = 'trialsphotos/')

	def __str__(self):
		return f'Фото испытаний {self.image.name}'

main/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView

from .models import *


class HomePageView(TemplateView):
	template_name = 'index.html'


class AboutPageView(TemplateView):
	template_name = 'about.html'


class PostListView(ListView):
	model = Post
	template_name = "blog.html"


class PostDetailView(DetailView):
	model = Post
	template_name = "blog_info.html"


class ProductListView(ListView):
	model = Product
	template_name = 'catalog.html'


class DocumentationBlockListView(ListView):
	model = DocumentationBlock
	template_name = 'documentation.html'


class TrialsPhotoListView(ListView):
	model = TrialsPhoto
	template_name = 'gallery.html'


class ContactPageView(TemplateView):
	template_name = 'contacts.html'

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="{% url 'home' %}">Главная</a>
                <span>&#062;</span>
                <a class="current_link" href="{% url 'about' %}">О Компании</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== ABOUT US START ========== -->

    <section class="about" style="background-image: url(/static/img/aboutusbg.jpg);">
        <div class="container">
            <div class="about_content">
                <h2 class="about_title">О Компании</h2>
                <p class="about_text">Производством органического удобрения “КМН” и биологически активного грунта “BIOZHER” занимается специально созданное для этого ООО “BIOZHER”. Продукция производится по лицензии ГНУ ВНИИМЗ – разработчика технологии, обеспечивающей гарантированное
                    обеззараживание птичьего помета (навоза) без использования ядохимикатов и превосходит по совокупности качеств исходное сырье в 2-4 раза.</p>
                <div class="about_link">
                    <a href="{% url 'documentation' %}">Подробнее</a>
                </div>
            </div>
            <div class="about_blackbg"></div>
        </div>
    </section>

    <!-- ========== ABOUT US END ========== -->

    <!-- ========== BIOZHER START ========== -->

    <section class="biozher">
        <div class="container">
            <div class="biozher_content">
                <div class="biozher_left">
                    <h2 class="biozher_title">Лучшие в природе</h2>
                    <p class="biozher_text">Биоудобрение произведенное на основе куриного помета с применением ЭМ (эффективные микроорганизмы) бактерий чрезвычайно полезно для плодородия почвы и воздействует на нее комплексно. Такое удобрение не только структурирует землю, но
                        и улучшает ее биохимический состав, увеличивает количество полезных микроорганизмов и червей, что неминуемо положительно отражается на плодородии каждой садовой, бахчевой и огородной культуры.</p>
                    <a href="{% url 'contacts' %}" class="biozher_link">Свяжитесь с нами и узнайте больше!</a>
                </div>
                <img class="biozher_right" src="{% static 'img/biozherbg.png' %}" alt="">
            </div>
        </div>
    </section>

    <!-- ========== BIOZHER END ========== -->

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BioZher</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/logo.png' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/slider.js' %}"></script>
</head>

<body>

    <!-- ========== NAV START ========== -->

    <nav class="nav">
        <div class="container">
            <div class="nav_content">
                <div class="logo">
                    <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
                <div class="nav_link-items">
                    <div class="nav_link-info">
                        <ul class="nav_list">
                            <li class="nav__item">
                                <a class="nav_link" href="{% url 'home' %}">Главная</a>
                            </li>
                            <li class="nav__item active">
                                <a class="nav_link has-subnav " href="{% url 'about' %}">О Компании</a>
                                <ul class="subnav">
                                    <li><a class="subnav_link" href="{% url 'documentation' %}">Документация</a></li>
                                    <li><a class="subnav_link" href="{% url 'gallery' %}">Фото Испытаний</a></li>
                                </ul>
                            </li>
                            <li class="nav__item">
                                <a class="nav_link" href="{% url 'products' %}">Продукция</a>
                            </li>
                            <li class="nav__item">
                                <a class="nav_link" href="{% url 'blog' %}">Блог</a>
                            </li>
                        </ul>
                        <div class="nav_contacts">
                            <a class="nav__contact" href="{% url 'contacts' %}">Контакты</a>
                            <span></span>
                            <a href="tel:+77022038282" class="nav__phone-num">+7 (702) 203-82-82</a>
                        </div>
                    </div>
                </div>
                <div class="menu-btn">
                    <div class="menu-btn__burger"></div>
                </div>
            </div>
        </div>
    </nav>

    <!-- ========== NAV END ========== -->

    {% block content %}

    {% endblock %}

<!-- ========== FOOTER START ========== -->

    <footer class="footer">
        <div class="container">
            <div class="footer_content">
                <div class="footer_logo-text">
                    <div class="footer_logo">
                        <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                    <div class="logo_text">
                        <p>Натуральные чистая экология и биологический грунт нового поколения продуктов</p>
                    </div>
                </div>
                <div class="footer_links">
                    <div class="footer_link">
                        <h3>Меню</h3>
                        <a href="{% url 'home' %}">Главная</a>
                        <a href="{% url 'about' %}">О Компании</a>
                        <a href="{% url 'products' %}">Продукция</a>
                        <a href="{% url 'blog' %}">Блог</a>
                        <a href="{% url 'contacts' %}">Контакты</a>
                    </div>
                    <div class="footer_contacts">
                        <h3>Контакты</h3>
                        <div class="footer_adress">
                            <span><i class="fas fa-map-marker-alt"></i></span>
                            <a target="_blank" href="https://goo.gl/maps/DEBgzT7VcQspiTVh7">Задний округ села "Мырзатай"</a>
                        </div>
                        <div class="footer_phone-num">
                            <span><i class="fas fa-phone-alt"></i></span>
                            <a href="tel:+77022038282">+7 (702) 203-82-82</a>
                        </div>
                        <div class="footer_mail">
                            <span><i class="fas fa-envelope"></i></span>
                            <a href="mailto:baurjan_82@bk.ru">baurjan_82@bk.ru</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- ========== FOOTER END ========== -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog.html
{% extends 'base.html' %}


{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="index.html">Главная</a>
                <span>&#062;</span>
                <a class="current_link" href="blog.html">Блог</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== BLOG START ========== -->
    <section class="blog">
        <div class="blog_container">
            <div class="blog_wrap">
                {% for post in object_list %}
                <div class="blog_post">
                    <div class="post_video">
                        <iframe width="560" height="315" src="{{ post.link_for_video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <div class="post_words">
                            <h1>{{ post.title }}</h1>
                            <p>{{ post.description }}</p>
                        </div>
                    </div>
                    <div class="post_btns">
                        <a class="btn_info" href="{% url 'blog_detail' post.pk %}">узнать больше</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- ========== BLOG END ========== -->
{% endblock %}

templates/blog_info.html
{% extends 'base.html' %}

{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="index.html">Главная</a>
                <span>&#062;</span>
                <a class="prev_link" href="blog.html">Блог</a>
                <span>&#062;</span>
                <a class="current_link" href="blog.html">{{ object.title }}</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== BLOG START ========== -->
    <section class="blog">
        <div class="blog_container">
            <div class="blog_wrap">
                <div class="blog_post2">
                    <div class="post_video">
                        <iframe height="315" src="{{ object.link_for_video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <div class="post_words">
                            <h1>{{ object.title }}</h1>
                            <p>{{ object.description }}</p>
                        </div>
                    </div>
                    <div class="post_btns">
                        <a class="btn_info" href="{% url 'blog' %}"> <i class="fas fa-arrow-left"></i> назад</a>
                    </div>
                </div>


            </div>
        </div>
    </section>

    <!-- ========== BLOG END ========== -->

{% endblock %}

templates/catalog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="index.html">Главная</a>
                <span>&#062;</span>
                <a class="current_link" href="catalog.html">Продукция</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== ABOUT US START ========== -->

    <section class="about" style="background-image: url(/static/img/catalog.jpg);">
        <div class="container">
            <div class="about_content">
                <h2 class="about_title">Экспорт продукции</h2>
                <p class="about_text">Продукция компании прошла испытания во многих аккредитованных лабораториях , на основании которых получено разрешение на ввоз в другие страны . В случае заинтересованности в дополнительной информации по экспорту продукции свяжитесь нами.</p>
                <div class="about_link">
                    <a href="{% url 'contacts' %}">Связаться с нами</a>
                </div>
            </div>
            <div class="about_blackbg"></div>
        </div>
    </section>

    <!-- ========== ABOUT US END ========== -->
    <!-- ========== CATALOG START ========== -->
    <section class="catalog">
        <div class="blog_container">
            <div class="catalog_body">
                <div class="catalog_title">
                    <h1>Наша продукция</h1>
                </div>
                <div class="catalog_wrap">
                    {% for product in object_list %}
                    <div class="catalog_item">
                        <div class="catalog_item_title">
                            <h1>{{ product.title }}</h1>
                            <p>{{ product.description }}</p>
                        </div>
                        <div class="catalog_item_img">
                            <img src="{{ product.image.url }}" alt="">
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!-- ========== CATALOG END ========== -->
{% endblock %}

templates/contacts.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="{% url 'home' %}">Главная</a>
                <span>&#062;</span>
                <a class="current_link" href="{% url 'contacts' %}">Контакты</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== CONTACTS START ========== -->

    <section class="contacts">
        <div class="container">
            <div class="contacts_title">
                <h2>Контакты</h2>
            </div>
            <div class="contacts_content">
                <div class="contacts_left">
                    <div class="contacts_phonenum-title">
                        <h3>Телефон</h3>
                        <a href="tel:+77022038282">+7 702 203 8282</a>
                        <a href="tel:+77076627090">+7 707 662 7090</a>
                        <a href="tel:87769627090">8 (776) 962-70-90</a>
                    </div>
                    <div class="contacts_mail-title">
                        <h3>Почта</h3>
                        <a href="mailto:baurjan_82@bk.ru">baurjan_82@bk.ru</a>
                        <a href="mailto:aidos@sknika.kz">aidos@sknika.kz</a>
                    </div>
                    <div class="contacts_place-title">
                        <h3>Адресс</h3>
                        <a target="_blank" href="https://goo.gl/maps/DEBgzT7VcQspiTVh7">Задний округ села "Мырзатай"</a>
                    </div>
                </div>
                <img class="contacts_right" src="{% static 'img/biglogo.png' %}" alt="">
            </div>
            <div class="contacts_map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d20766.720862031285!2d71.4330557949523!3d43.089127192776886!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDPCsDA1JzEwLjIiTiA3McKwMjYnMjkuMiJF!5e0!3m2!1sru!2skz!4v1620880008046!5m2!1sru!2skz"
                    style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </section>

    <!-- ========== CONTACTS END ========== -->
{% endblock %}

templates/documentation.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="index.html">Главная</a>
                <span>&#062;</span>
                <a class="prev_link" href="about.html">О Компании</a>
                <span>&#062;</span>
                <a class="current_link" href="{% url 'documentation' %}">Документация</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== DOCUMENTATIONS START ========== -->

    <section class="document">
        <div class="container">
            <div class="document_title">
                <h2>Документация</h2>
            </div>
            <div class="document_content">
                {% for document_block in object_list %}
                <div class="document_item" data-name="accordeon-title">
                    <h3 class="document_title">{{ document_block.title }}</h3>
                </div>
                <div class="document_item document_item-content hidden">
                    {% for document_item in document_block.documentationblockitem_set.all %}
                    <div class="document_info">
                        <div class="document_info-icon">
                            <img src="{% static 'img/pdficon.png' %}" alt="">
                        </div>
                        <div class="document_info-name">
                            <a target="_blank" download href="{{ document_item.file.url }}" data-filename="Сертификат из Алматы">
                                Посмотреть
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- ========== DOCUMENTATIONS END ========== -->

{% endblock %}

templates/gallery.html
{% extends 'base.html' %}

{% block content %}

    <!-- ========== PAGES DEPARTMENT START ========== -->

    <section class="pagedepart">
        <div class="container">
            <div class="pagedepart_content">
                <a class="prev_link" href="index.html">Главная</a>
                <span>&#062;</span>
                <a class="prev_link" href="about.html">О Компании</a>
                <span>&#062;</span>
                <a class="current_link" href="{% url 'gallery' %}">Фото Испытаний</a>
            </div>
        </div>
    </section>

    <!-- ========== PAGES DEPARTMENT END ========== -->

    <!-- ========== PHOTO TEST START ========== -->

    <section class="photo">
        <div class="container">
            <div class="photo_title">
                <h2>Фото Испытаний</h2>
            </div>
            <div class="photo_content">
                {% for photo_item in object_list %}
                <div class="photo_item">
                    <div class="photo_img">
                        <img src="{{ photo_item.image.url }}" alt="">
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- ========== PHOTO TEST END ========== -->

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- ========== HEADER START ========== -->
    <header class="header">
        <div class="header_slider">
            <div class="header_slider-item slider-item" style="background-image: url(/static/img/headerbg.jpg);">
                <div class="slider-item__content">
                    <div class="slider_info">
                        <div class="slider-item__info-suptitle">
                            Натуральные чистая экология и биологический грунт нового поколения продуктов
                        </div>
                        <div class="slider-item__info-suptext">
                            “Biozher” позволяет увеличить урожай на 25-30% при сокращении периода созревания на 5-15 дней!
                        </div>
                        <div class="slider-item__info-link">
                            <a href="{% url 'about' %}">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header_slider-item slider-item" style="background-image: url(/static/img/nitratbg.jpg);">
                <div class="slider-item__content">
                    <div class="slider_info">
                        <div class="slider-item__info-suptitle">
                            Биологический грунт <br> нового поколения
                        </div>
                        <div class="slider-item__info-suptext">
                            Обладает увеличенным содержанием полезной микрофлоры без запахов
                        </div>
                        <div class="slider-item__info-link">
                            <a href="{% url 'about' %}">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ========== HEADER END ========== -->

    <!-- ========== CHOOSE START ========== -->

    <section class="choose">
        <div class="container">
            <div class="choose_title">
                <h2>Почему все выбирают “Biozher”?</h2>
            </div>
            <div class="choose_content">
                <div class="choose_top-items">
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/hand.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">Органические соединения</h3>
                        <p class="choose_item-text">Содержит основные элементы питания растений (азот, фосфор, калий) и микроэлементы (медь, цинк, бор, магний и др.)</p>
                    </div>
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/ground.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">Полезная микрофлора</h3>
                        <p class="choose_item-text">В ходе биоферментации многократно увеличивается содержание полезной (аэробной) микрофлоры – основы жизни плодородного слоя земли.</p>
                    </div>
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/plants.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">отсутствие семян сорных растений</h3>
                        <p class="choose_item-text">Технология глубокой аэробной биоферментации позволяет обеспечить 100% отсутствие семян сорных растений в действующем веществе (органическом удобрении КМН).</p>
                    </div>
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/smell.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">отсутствие запахов</h3>
                        <p class="choose_item-text">Характерные для органической продукции неприятные запахи пропадают в результате активной деятельности микрофлоры.</p>
                    </div>
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/clear plants.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">чистота балтики</h3>
                        <p class="choose_item-text">Технология “Биозём” дает 100% гарантию обеззараживания патогенной микрофлоры, что позволяет легально применять продукцию на сельскохозяйственных угодьях, тем самым сокращая вероятность попадания биогенов в воды Балтийского Моря.</p>
                    </div>
                    <div class="choose_item">
                        <div class="choose_item-img">
                            <img src="{% static 'img/credibility.png' %}" alt="">
                        </div>
                        <h3 class="choose_item-title">множественный отбор</h3>
                        <p class="choose_item-text">Наши продукты заверены лучшими профессорами со всего Казахстана.И мы с точностью в 100% заверяем что наши продукты прошли множественный отбор и не причинят вреда вашим землям.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ========== CHOOSE END ========== -->

    <!-- ========== NITRAT START ========== -->

    <section class="nitrat">
        <div class="container">
            <div class="nitrat_content">
                <div class="nitrat_info">
                    <div class="nitrat_info_firstitem">
                        <h2 class="nitrat_title">Урожай без нитратов!</h2>
                        <p class="nitrat_text">Все овощи, ягоды и фрукты, выращенные на КМН, проверены на содержание нитратов. Фактическое их содержание значительно ниже предельно допустимых норм.</p>
                        <a href="{% url 'documentation' %}" class="nitrat_link">Документация</a>
                    </div>
                    <div class="nitrat_info_seconditem">
                        <h2 class="nitrat_title">“BIOZHER” работает!</h2>
                        <p class="nitrat_text">Практические испытания КМН проведены на разных культурах в большом количестве сельхозпредприятий и питомников Жамбылской области. Результаты испытаний во всех случаях положительные, а в некоторых – превзошли все ожидания. Кроме
                            этого, мы провели собственные испытания на садовом участке во Байзакском районе.</p>
                        <a href="{% url 'gallery' %}" class="nitrat_link">Фотографии испытаний</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ========== NITRAT END ========== -->

{% endblock %}